Feature/add main page -> main
Temagavr/TL-learning pull request #1
Opened 2021-11-09 18:52 UTC by Temagavr

Сверстана главная страница

2021-11-10 07:52 UTC, Temagavr commented
Не сделано открывание модального окна с логинацией при нажатии на кнопку "Войти" в header. 
Проблема в том, что т.к. header переиспользуется он импортируется в app.module и я не знаю как обратиться к модальному окну, которое находится в home-component, потому что в app-component код страницы появляется через router-outlet и к как таковому home-component не получится обратиться.

2021-11-10 14:56 UTC, Temagavr commented
Как возможное решение - сделать модуль для общих компонентов и экспоритровать компоненты как header и использовать его непосредственно в компоненте страницы, а не в app.component

2021-11-10 18:57 UTC, egoshin-igor requested changes

2021-11-10 18:57 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/home/day-recipe/day-recipe.component.ts
> +import { DayRecipe } from '../DayRecipe';
![image](https://user-images.githubusercontent.com/24194554/141162176-ce4862bd-de8e-4156-a653-e02a4700ff84.png)
![image](https://user-images.githubusercontent.com/24194554/141162284-51d87168-0978-4b5a-ac1e-4102c1fbb63e.png)

Что то странный импорт. Не так должно быть? У меня билд ругается даже

2021-11-10 18:57 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/home/day-recipe.js
> +Object.defineProperty(exports, "__esModule", { value: true });
Зачем этот файл?

2021-11-10 18:57 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/home/day-recipe.js.map
> +{"version":3,"file":"DayRecipe.js","sourceRoot":"","sources":["DayRecipe.ts"],"names":[],"mappings":""}
Зачем этот файл?

2021-11-10 18:57 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/home/day-recipe/day-recipe.component.css
> +.day-recipe-comp {
![image](https://user-images.githubusercontent.com/24194554/141162712-2707e14a-c265-4f3a-b520-1c5c5f682771.png)
Варнинги починить может? Не уверен в чем именно проблема только)

2021-11-10 18:57 UTC, egoshin-igor commented on .gitignore
> +## Ignore Visual Studio temporary files, build results, and
Пройдись по стилям текстов. У "Готовь и делись рецептами", например, не тот стиль.
![image](https://user-images.githubusercontent.com/24194554/141164108-e3fdfa08-3bd6-45f8-9f2c-d259df4aba80.png)
![image](https://user-images.githubusercontent.com/24194554/141164180-459997c6-8557-4d4e-b1ed-b54c53b6cbdc.png)

2021-11-10 18:57 UTC, egoshin-igor commented on .gitignore
> +## Get latest from https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
Добавил пример фикса модального окна - https://github.com/Temagavr/TL-learning/tree/feature/add_main_page_modal_fix_example

Смотри. У тебя модальные окна как директивы не являются независимыми и самодостаточными(isLoginShowed вообще в home находится). Это в скинутой ветке я +- поправил. Решение с хедером тоже там есть. Такое решение получилось. Может что лучше можно придумать, не знаю. 
Но в любом случае - компоненты должны быть независимыми - не полагаться на переменные извне. Еще увидел что стили все почти в общих styles.css. Если есть какие то не общие стили, то лучше их вынести обратно в компонент. модалки общие, если примешь мой пример решения тоже тогда нужно перенести из home в common. Т.к. они у тебя на всех страницах будут использовать, не только в home. Да и в home у тебя логики работы с модалкой не должно быть особо, т.к. потом их придется дублировать на других страницах. Либо в app.component либо в самой модалке.

2021-11-10 18:57 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/app-routing.module.ts
> +  //{ path: '', loadChildren: () => import('./pages/home/home.module').then(m => m.HomeModule), pathMatch: 'full' },
комментарии лишние если не нужны, то лучше убрать

2021-11-11 13:47 UTC, Temagavr commented
Убрал лишние комментарии
Сделал модалки по примеру
Поправил шрифты
Убрал варнинг в day-recipe.component.css
Странный импорт забыл поправить перед тем как залить, сейчас все нормально должно быть 
Лишние js файлы не знаю даже откуда, странные какие то о_О

2021-11-11 15:22 UTC, egoshin-igor approved these changes

2021-11-11 15:22 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/app.component.html
> +  <app-login-modal (onClose)="doSmthOnCloseLoginModal()" (onShow)="doSmthOnOpenLoginModal()" (onSwitchToRegistration)="switchToRegistration()" (onLoginClick)="doSmthOnLoginClick()"></app-login-modal>
doSmthOnOpenLoginModal если что как пример только был. Если они не нужны то можно и убрать

2021-11-12 08:19 UTC, merged