Feature/add recipe likes -> main
Temagavr/TL-learning pull request #12
Opened 2021-12-26 18:39 UTC by Temagavr

Добавил функционал лайков

Сделал подсчет лайков через сущность Recipe и обновление у нее счетчика лайков, возможно это плохое решение, если да, то напиши как лучше сделать

2021-12-28 07:20 UTC, egoshin-igor requested changes

2021-12-28 07:20 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            )
скобка. ...Service )

2021-12-28 07:20 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            RecipeLike recipeLike = new RecipeLike(userId, recipeId);
если тип понятен, то можно var писать. Т.к. справа итак new RecipeLike

2021-12-28 07:20 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            recipe.AddLike();
А эта штука зачем используется?

2021-12-28 07:20 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            RecipeLike recipeLike = new RecipeLike(userId, recipeId);
Если лайк от данного пользователя уже есть ты удаляешь и добавляешь сущность. Может просто поле будешь обновлять в RecipeLike ?

2021-12-28 07:20 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            recipe.AddLike();
У тебя уже есть RecipeLike

2021-12-28 07:20 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Infrastructure/Repositories/RecipeLikeRepository.cs
> +            if (userId != 0)
опять проверка на ноль. Зачем ? Просто ищи по userId.

2021-12-28 07:20 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/HomeModule/HomeController.cs
> +            if (recipe != null)
Всю конструкцию можно заменить на recipe?.Map();

2021-12-28 07:20 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeDetailsModule/RecipeDetailsController.cs
> +                );
скобка не в том месте. Выше писал

2021-12-28 07:20 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeLikesModule/RecipeLikesController.cs
> +            await _recipeService.AddLike(recipeId, Convert.ToInt32(User.FindFirstValue(Claims.UserId)));
Чтобы каждый раз не писать User.FindFirstValue(Claims.UserId) обычно создают базовый контроллер и выносят туда такие штуки

2021-12-28 08:42 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            )
++

2021-12-28 08:42 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            RecipeLike recipeLike = new RecipeLike(userId, recipeId);
++

2021-12-28 08:43 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Infrastructure/Repositories/RecipeLikeRepository.cs
> +            if (userId != 0)
++

2021-12-28 08:45 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeDetailsModule/RecipeDetailsController.cs
> +                );
++

2021-12-28 08:54 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/HomeModule/HomeController.cs
> +            if (recipe != null)
++

2021-12-28 15:35 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            recipe.AddLike();
++

2021-12-28 21:36 UTC, egoshin-igor requested changes

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Domain/Entities/Recipes/RecipeLike.cs
> +                int userId,
тут явно слишком много пробелов

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Domain/Entities/Recipes/RecipeLike.cs
> +            )
скобка не там

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        Task<RecipeLike> GetByUserIdRecipeId(int userId, int recipeId);
GetByUserIdAndRecipeId

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        Task<List<RecipeLike>> GetRecipeLikes(int recipeId);
GetByRecipeId

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        Task<List<RecipeLike>> GetUserLikedRecipes(int userId);
GetByUserId

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        void AddLike(RecipeLike recipeLike);
Просто Add

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        void RemoveLike(RecipeLike recipeLike);
Просто Remove

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Infrastructure/Configurations/RecipeLikeConfiguration.cs
> +            /*
комментарии просто так не оставлять лучше

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/common/recipe-card/recipe-card.component.ts
> +  public async likeRecipe() {
возвращаемый тип не написан

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/common/recipe-card/recipe-like.service.ts
> +  public async likeRecipe(recipeId: number) {
с возвзвращаемым типом надо разобраться

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/common/shared.module.ts
> +  providers:[RecipeLikeService]
форматирование

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeCreateUpdateModule/RecipeCreateUpdateMapper.cs
> +            result.Steps = new List<Application.Recipes.RecipeDtos.RecipeStepDto>();
ты и так на строку ниже создаешь список. Не нужно тут через new создавать. С ингредиентами выше так же

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeCreateUpdateModule/RecipeCreateUpdateMapper.cs
> +            result.Steps = new List<Application.Recipes.RecipeDtos.RecipeStepDto>();
И тэги тоже

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeDetailsModule/RecipeDetailsMapper.cs
> +            if (likeRecipe.Count > 0)
это можно переписать. recipeDetailsDto.IsLiked = likeRecipe.Count > 0;

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeDetailsModule/RecipeDetailsMapper.cs
> +            if (likeRecipe.Count > 0)
да и вообще по другому сделать. У пользователя не может быть больше одного лайка
recipeDetailsDto.IsLiked = recipeLikes.Any( x => x.UserId == userId )

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeDetailsModule/RecipeDetailsMapper.cs
> +            var likeRecipe = recipeLikes.Where(r => r.UserId == userId).ToList();
var --> явный тип

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeDetailsModule/RecipeDetailsMapper.cs
> +            var likeRecipe = recipeLikes.Where(r => r.UserId == userId).ToList();
likeRecipe как будто один элемент. И вообще не отражает по названию содержимое.
userLikes может?

2021-12-28 21:36 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeLikesModule/RecipeLikesController.cs
> +            _recipeService.AddLike(recipeId, Convert.ToInt32(User.FindFirstValue(Claims.UserId)));
Convert.ToInt32(User.FindFirstValue(Claims.UserId)) штуки так и не вынес еще в BaseController

2021-12-30 13:53 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Domain/Entities/Recipes/RecipeLike.cs
> +            )
++

2021-12-30 13:53 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Domain/Entities/Recipes/RecipeLike.cs
> +                int userId,
++

2021-12-30 13:54 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        void AddLike(RecipeLike recipeLike);
++

2021-12-30 13:54 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        Task<List<RecipeLike>> GetUserLikedRecipes(int userId);
++

2021-12-30 13:54 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        Task<List<RecipeLike>> GetRecipeLikes(int recipeId);
++

2021-12-30 13:54 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        Task<RecipeLike> GetByUserIdRecipeId(int userId, int recipeId);
++

2021-12-30 13:54 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Domain/Repositories/IRecipeLikeRepository.cs
> +        void RemoveLike(RecipeLike recipeLike);
++

2021-12-30 14:02 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeDetailsModule/RecipeDetailsMapper.cs
> +            var likeRecipe = recipeLikes.Where(r => r.UserId == userId).ToList();
++

2021-12-30 14:05 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Infrastructure/Configurations/RecipeLikeConfiguration.cs
> +            /*
++

2021-12-30 14:06 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeCreateUpdateModule/RecipeCreateUpdateMapper.cs
> +            result.Steps = new List<Application.Recipes.RecipeDtos.RecipeStepDto>();
++

2021-12-30 14:19 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeDetailsModule/RecipeDetailsMapper.cs
> +            var likeRecipe = recipeLikes.Where(r => r.UserId == userId).ToList();
++

2021-12-30 14:19 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeDetailsModule/RecipeDetailsMapper.cs
> +            if (likeRecipe.Count > 0)
++

2021-12-30 14:22 UTC, Temagavr commented on CookingWebsite/CookingWebsite/ClientApp/src/app/common/recipe-card/recipe-card.component.ts
> +  public async likeRecipe() {
++

2021-12-30 14:23 UTC, Temagavr commented on CookingWebsite/CookingWebsite/ClientApp/src/app/common/recipe-card/recipe-like.service.ts
> +  public async likeRecipe(recipeId: number) {
++

2021-12-30 14:23 UTC, Temagavr commented on CookingWebsite/CookingWebsite/ClientApp/src/app/common/shared.module.ts
> +  providers:[RecipeLikeService]
++

2021-12-30 17:34 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeLikesModule/RecipeLikesController.cs
> +            _recipeService.AddLike(recipeId, Convert.ToInt32(User.FindFirstValue(Claims.UserId)));
++

2021-12-30 17:35 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeLikesModule/RecipeLikesController.cs
> +            await _recipeService.AddLike(recipeId, Convert.ToInt32(User.FindFirstValue(Claims.UserId)));
++

2022-01-02 11:28 UTC, merged