Feature/add recipe favourites page backend -> main
Temagavr/TL-learning pull request #15
Opened 2022-01-11 15:44 UTC by Temagavr

Добавил получение избранных рецептов пользователя

2022-01-12 08:46 UTC, egoshin-igor approved these changes

2022-01-12 08:46 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            if(recipeFavourites != null)
Он null может быть? Хороший тон/правило - всегда в методах со списками как минимум возвращать пустой список

2022-01-12 08:46 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +                    recipes.Add(await _recipeRepository.GetById(favourite.RecipeId));
Вместо цикла групповую операцию может? GetByIds(  recipeIds ) ?

2022-01-12 08:46 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Infrastructure/Repositories/RecipeFavouriteRepository.cs
> +            query = query.Where(x => x.UserId == userId).Skip(skip).Take(take);
OrderBy добавь какой нить, чтобы порядок всегда одинаковый был. Да хотя бы по Id

2022-01-12 08:46 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/user-favourites/user-favourites.component.ts
> +    this.userFavouritesService.getUserFavourites(skip, 2).then((recipeCards: RecipeCard[]) => {
магическое число два. Вынести в константу метода?

2022-01-12 08:46 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/UserFavouritesController.cs
> +            List<Recipe> recipe = await _recipeService.GetUserFavourites(skip, take, GetAuthorizedUserId());
GetAuthorizedUserId в переменную в начала сохранить может?

2022-01-12 08:46 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/UserFavouritesController.cs
> +            [FromQuery] string searchString)
searchString нигде не используется в методе

2022-01-12 08:46 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/UserFavouritesController.cs
> +            List<Recipe> recipe = await _recipeService.GetUserFavourites(skip, take, GetAuthorizedUserId());
recipe -> recipes

2022-01-12 08:46 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/UserFavouritesController.cs
> +            List<RecipeLike> userLikes = await _recipeLikeRepository.GetByUserId(GetAuthorizedUserId());
Обычно такие штуки в отдельный класс выводят в рамках модуля текущего. Что то типа RecipeCardBuilder
метод Build(recipes), который возвращает список RecipeCardDto

2022-01-12 11:53 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            if(recipeFavourites != null)
++

2022-01-12 11:54 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Infrastructure/Repositories/RecipeFavouriteRepository.cs
> +            query = query.Where(x => x.UserId == userId).Skip(skip).Take(take);
++

2022-01-12 11:54 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/UserFavouritesController.cs
> +            [FromQuery] string searchString)
++

2022-01-12 11:55 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/UserFavouritesController.cs
> +            List<Recipe> recipe = await _recipeService.GetUserFavourites(skip, take, GetAuthorizedUserId());
++

2022-01-12 11:56 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/UserFavouritesController.cs
> +            List<Recipe> recipe = await _recipeService.GetUserFavourites(skip, take, GetAuthorizedUserId());
++

2022-01-12 11:56 UTC, Temagavr commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/user-favourites/user-favourites.component.ts
> +    this.userFavouritesService.getUserFavourites(skip, 2).then((recipeCards: RecipeCard[]) => {
++

2022-01-12 18:46 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/UserFavouritesController.cs
> +            List<RecipeLike> userLikes = await _recipeLikeRepository.GetByUserId(GetAuthorizedUserId());
++

2022-01-12 19:04 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +                    recipes.Add(await _recipeRepository.GetById(favourite.RecipeId));
++

2022-01-14 07:31 UTC, egoshin-igor requested changes

2022-01-14 07:31 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Infrastructure/Repositories/RecipeRepository.cs
> +                .Where(x => recipeIds.Contains(x.Id)).OrderBy(r => r.Id);
Тут внутри OrderBy не нужен уже

2022-01-14 07:31 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/RecipeCardMapper.cs
> +            IRecipeLikeRepository recipeLikeRepository,
Погоди, погоди. В маппер только данные идут, а не сами репозитории. Это в билдере должно быть.
Т.е. тут два варианта. Сделать маппер для одного рецепта и туда кол-во лайков отправлять сразу, а в билдере в фориче вызывать мап. Второй вариант групповая операция, что сложнее. Можешь пока первый

2022-01-14 07:31 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/RecipeCardBuilder.cs
> +    public class RecipeCardBuilder
Где интерфейс? Его еще в di надо добавить в UserFavouritesBindings и через конструктор контроллера получить
IRecipeCardBuilder

2022-01-14 09:17 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Infrastructure/Repositories/RecipeRepository.cs
> +                .Where(x => recipeIds.Contains(x.Id)).OrderBy(r => r.Id);
++

2022-01-14 09:21 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/RecipeCardBuilder.cs
> +    public class RecipeCardBuilder
++

2022-01-14 09:59 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/UserFavouritesModule/RecipeCardMapper.cs
> +            IRecipeLikeRepository recipeLikeRepository,
++

2022-01-14 10:09 UTC, merged