Feature/add recipe backend -> main
Temagavr/TL-learning pull request #7
Opened 2021-12-06 13:31 UTC by Temagavr

Сделано добавление рецепта без тегов и с захардкорженным автором на backend'e

2021-12-07 08:24 UTC, egoshin-igor requested changes

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Files/FileService.cs
> +    public class FileService : IFileService
Сервис - это выдумка с методами, выполняющую какую то логику. В твоем случае это не сервис, а какая то сущность. Что то вроде просто File + IFormFile чисто штука, относящаяся к Api, а не application. Поэтому метод CreateAsync я бы сделал где нибудь в апи, а он бы уже возвращал File, находящийся в app.

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeDtos/AddRecipeDto.cs
> +        public FileService Image { get; set; }
тут в итоге будет просто File(или другое название какое придумаешь)

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +        private const string ImagesPath = @"E:\TL-learning\CookingWebsite\CookingWebsite\ClientApp\src\assets\recipes";
это вынести лучше в конфиги: в appsettings. Как с конфигами работать, возможно в моем репозитории можешь найти

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            var imageSaveResult = await SaveAsync(addRecipeDto.Image, ImagesPath);
сохранение рецепта и ImagesPath в отдельном сервисе как раз лучше бы. Как я и говорил - в FileStorageService или FileStorageManager. Как хочешь называй. Ток там путь на до изображений, а просто путь до хранилища и т.п. Я тебе уже рассказывал

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            recipe.SetIngredients(new List<RecipeIngredient>());
эти штуки лучше сразу в конструктор присылать. Не нужно recipe.Id в конструктор подсущностей слать. Он их потом сам определит. Т.е. заранее создаешь подсущности и отправляешь в конструктор

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            recipe.SetIngredients(new List<RecipeIngredient>());
Через linq лучше все это

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +                //_recipeRepostitory.AddRecipeStep(step);
комментарии если не используются, то лучше убрать

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/recipe-create/recipe-create.component.ts
> +      var stepDto: AddRecipeStepDto = {
var лучше не юзать. let иди const

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/recipe-create/recipe-create.component.ts
> +      var ingredientsFront = ingredient.items.trim().split('\n');
типы лучше явно прописывать

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/recipe-create/recipe-create.component.ts
> +      for (var ingrt of ingredientsFront) {
вместо for есть метод map

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/recipe-details/recipe-details.component.ts
> +      this.recipeCard = {
мы ж вроде в одном из пулл реквестов решили, что можно не иницилизировать поле в начале

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/Dtos/AddRecipeStepDto.cs
> +        public int StepNum { get; set; }
названия полей лучше не сокращать. Путаницу только вызывает

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeController.cs
> +            recipeDto.Image = await FileService.CreateAsync(files[0]);
вместо этого просто в метод Map отправляй file

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeMapper.cs
> +            recipeDto.Title = recipe.Title;
У тебя и тут и там recipeDto. Назови лучше это поле recipeDto -> result

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeMapper.cs
> +            foreach (RecipeIngredientDto ingredient in recipe.RecipeIngredient)
Списки в множественном числе. recipe.RecipeIngredient ->recipe.Ingredients.
Не надо писать Recipe в recipe.RecipeIngredient, и так понятно по контексту что это ингредиенты рецепта

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeMapper.cs
> +            foreach (RecipeIngredientDto ingredient in recipe.RecipeIngredient)
попробуй в linq вида
result.Ingredients = recipe.Ingredients.Select(x => new BlaBla
{
____Name = x.Name,
____Steps = x.Steps.Select(y => ...)
}

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeMapper.cs
> +            for (int stepIndex = 0; stepIndex < recipe.Steps.Count; stepIndex++ )
индекс тож в linq есть. Если писать что то вроде steps.Select( (y, yi) => ...) Чет такое вродь

2021-12-07 08:24 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/ApplicationBindings.cs
>  ﻿using CookingWebsite.Application.Account;
И еще пиши, когда правки делаешь под каждым комментарием плюсик, чтобы я понимал, что ты поправил.

2021-12-07 14:23 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeMapper.cs
> +            recipeDto.Title = recipe.Title;
+

2021-12-07 14:23 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeMapper.cs
> +            foreach (RecipeIngredientDto ingredient in recipe.RecipeIngredient)
++

2021-12-07 14:24 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/ApplicationBindings.cs
>  ﻿using CookingWebsite.Application.Account;
++

2021-12-07 15:50 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeMapper.cs
> +            foreach (RecipeIngredientDto ingredient in recipe.RecipeIngredient)
++

2021-12-07 15:50 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeMapper.cs
> +            for (int stepIndex = 0; stepIndex < recipe.Steps.Count; stepIndex++ )
++

2021-12-07 18:06 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Files/FileService.cs
> +    public class FileService : IFileService
++

2021-12-07 18:10 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeDtos/AddRecipeDto.cs
> +        public FileService Image { get; set; }
++

2021-12-08 11:10 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            var imageSaveResult = await SaveAsync(addRecipeDto.Image, ImagesPath);
++

2021-12-08 11:13 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +                //_recipeRepostitory.AddRecipeStep(step);
++

2021-12-08 11:17 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/Dtos/AddRecipeStepDto.cs
> +        public int StepNum { get; set; }
++

2021-12-08 11:18 UTC, Temagavr commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/recipe-create/recipe-create.component.ts
> +      var ingredientsFront = ingredient.items.trim().split('\n');
++

2021-12-08 11:18 UTC, Temagavr commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/recipe-create/recipe-create.component.ts
> +      var stepDto: AddRecipeStepDto = {
++

2021-12-08 13:10 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +            recipe.SetIngredients(new List<RecipeIngredient>());
++

2021-12-08 13:13 UTC, Temagavr commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/recipe-details/recipe-details.component.ts
> +      this.recipeCard = {
Тут иначе он ругается что пытается взять от пустоты поля, я так понимаю что он быстрее отправляет данные в компонент чем получает их с backend'a

2021-12-08 14:21 UTC, Temagavr commented on CookingWebsite/CookingWebsite/Modules/RecipeModule/RecipeController.cs
> +            recipeDto.Image = await FileService.CreateAsync(files[0]);
++

2021-12-08 14:22 UTC, Temagavr commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/recipe-details/recipe-details.component.ts
> +      this.recipeCard = {
И такая же проблема на главной странице, картинку тогда не получается получить и отобразить

2021-12-08 14:30 UTC, Temagavr commented on CookingWebsite/CookingWebsite/ClientApp/src/app/pages/recipe-create/recipe-create.component.ts
> +      for (var ingrt of ingredientsFront) {
++

2021-12-08 14:31 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +        private const string ImagesPath = @"E:\TL-learning\CookingWebsite\CookingWebsite\ClientApp\src\assets\recipes";
Не нашел примера, а как адекватно сделать не придумал

2021-12-09 07:27 UTC, egoshin-igor approved these changes

2021-12-09 07:27 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Files/FileService.cs
> +        private const string Storage = @"E:\TL-learning\CookingWebsite\CookingWebsite\ClientApp\src\assets";
Это временно же ты прям в репозиторий сохраняешь файлы? Потом лучше в отдельный storage с отдельным контроллером сделать

2021-12-09 07:27 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Files/FileService.cs
> +            const string imagesPath = Storage + "\\recipes";
тут этот сервис лучше сделать независимым от рецептов. и поэтому путь указывать лучше вторым параметром метода - file, relativePath

2021-12-09 07:27 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +                            y.Name,
4 пробела достаточно. 8 много

2021-12-09 07:27 UTC, egoshin-igor commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +                likesCount: 0,
При создании рецепта все равно не может быть кол-во лайков и избранных больше нуля. Поэтому я бы приравнивание их нулю сделал бы внутри конструктор. А тут убрал бы вовсе

2021-12-09 09:04 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +                            y.Name,
++

2021-12-09 09:04 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +                likesCount: 0,
++

2021-12-09 09:10 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Files/FileService.cs
> +            const string imagesPath = Storage + "\\recipes";
++

2021-12-09 09:49 UTC, Temagavr commented on CookingWebsite/CookingWebsite.Application/Recipes/RecipeService.cs
> +        private const string ImagesPath = @"E:\TL-learning\CookingWebsite\CookingWebsite\ClientApp\src\assets\recipes";
++

2021-12-09 10:08 UTC, merged